matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: mUJs+jnBh8hBEeKHBJuL7hl4MqGXMbuG9DjxdNRe5LhkMR9cc5fjLnuoBwLGDkh2tNooDsfsInBeh/EoasL62spWL4FijahBliaT3lypoxFqI0PWzHdEUiKg1w3lagJGZCw2/TbVSqXAoG5penmqTUqC82GHCKpIyRpoC833ae8djuvRKxM1cE84vji/r0XaC6jPorQSsXF1NW5yZ+kZaPsMXdIeN/mNmCoq7pVYQ7XMlgkV2PXvX8KCG+u+6JfdkCtddr6Icj2uErwJkilFNER2G1LFwn/JWV8RaiVpabtUQivsjiGOsAy0jlRu4Hd13LR2adnFASKMRJaku+XUjODG/s2wc1xayjE9yRrvkky8QLSXNctBOn09qWc/fDfn51BEfOmP4vHhfZl7AG8Sb4uojIVTS2m59xX1gRol0/717vCEUQNS5xysv3qZbSsGoWjQC74DLgPuS4RoC35hvphkQmNDYTxmMz5DHMprqpA8YXVuO+jV3esnxJ7zNr0lQakEQYmg8qcQ7nbpuBoRmnXJHP4n/8/5PWcpc/KGtoDnV9nxwEXsv6HcPTvE8ALFhvJe3eDPxu5Zjakg03V2SBhKsp8CRJ2DURWDv5LDK30rmqq32Bfxn/qIhGrX69mMPQhgfE6gvJQXHeBo2YKVOJ5h0hBc8/2CAp9xF64slIs=
